name: Github Work
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
  repository_dispatch:
    types: [trigger-from-AAAA]
jobs:
  GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build Environments
        run: |
          sudo apt-get update
          sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common